server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    charset utf-8;

    location = /mail/config-v1.1.xml {
        default_type application/xml;
        add_header Cache-Control "public, max-age=3600";
        try_files /mail/config-v1.1.xml =404;
    }

    location = /.well-known/autoconfig/mail/config-v1.1.xml {
        default_type application/xml;
        add_header Cache-Control "public, max-age=3600";
        try_files /.well-known/autoconfig/mail/config-v1.1.xml =404;
    }

    location / {
        return 404;
    }
}
