"""Samba service — LDAP-aligned identity (Authentik password for bootstrap user), homes."""
from __future__ import annotations

import os
from pathlib import Path

from setup.service import Service, VolumeDir
from setup.storage_layout import USERS_ROOT, ensure_storage_layout
from setup.ui import info, ok, section
from setup.utils import gen_secret


def _write_ldap_env(env: dict) -> None:
    """Env consumed by entrypoint for LDAP + bootstrap SMB user (NTLM needs local passdb)."""
    ldap_pass_path = Path("./volumes/secrets/ldap_service_password")
    ldap_pass = ldap_pass_path.read_text(encoding="utf-8").strip() if ldap_pass_path.is_file() else ""
    admin_pass_path = Path("./volumes/secrets/homelab_password")
    admin_pass = admin_pass_path.read_text(encoding="utf-8").strip() if admin_pass_path.is_file() else ""
    username = (env.get("HOMELAB_USERNAME") or "admin").strip()

    lines = [
        "# Generated by samba/setup.py — do not edit.",
        f"HOMELAB_USERNAME={username}",
        f"HOMELAB_PASSWORD={admin_pass}",
        "LDAP_SERVER=ldap://authentik-ldap:3389",
        "LDAP_BASE_DN=dc=ldap,dc=goauthentik,dc=io",
        "LDAP_BIND_DN=cn=ldapservice,ou=users,dc=ldap,dc=goauthentik,dc=io",
        f"LDAP_BIND_PASSWORD={ldap_pass}",
    ]
    path = Path("./samba/volumes/config/samba.env")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(path, 0o600)


class SambaService(Service):
    name = "samba"
    volume_dirs = [
        VolumeDir("./samba/volumes/data", mode=0o755),
        VolumeDir("./samba/volumes/data/private", mode=0o700),
        VolumeDir("./samba/volumes/data/lock", mode=0o755),
        VolumeDir("./samba/volumes/config", mode=0o700),
    ]

    def setup(self, env: dict) -> None:
        super().setup(env)
        section("Preparing Samba + shared storage...", emoji="📁")
        private = "./samba/volumes/data/private"
        os.makedirs(private, mode=0o700, exist_ok=True)
        try:
            os.chmod(private, 0o700)
        except OSError:
            pass

        gen_secret("ldap_service_password", 32)

        puid = int(env.get("PUID") or os.environ.get("PUID") or "1000")
        pgid = int(env.get("PGID") or os.environ.get("PGID") or "1000")
        ensure_storage_layout(puid, pgid)
        # Ensure bootstrap admin home exists
        admin = (env.get("HOMELAB_USERNAME") or "admin").strip()
        home = os.path.join(USERS_ROOT, admin)
        os.makedirs(home, mode=0o700, exist_ok=True)
        try:
            os.chown(home, puid, pgid)
            os.chmod(home, 0o700)
        except OSError:
            pass

        _write_ldap_env(env)
        ok("Samba storage and LDAP/bootstrap env ready")
        info(
            "SMB is limited to Authentik group homelab-admins (NTLM passdb). "
            f"Passwords sync via host-api; bootstrap user ({admin}) "
            "also seeded from HOMELAB_PASSWORD. No per-user SMB quota."
        )
        info(f"SMB private: \\\\<IP>\\<username>  → {USERS_ROOT}/<username>")
        info("SMB shared:  \\\\<IP>\\shared      → ./storage/shared")


service = SambaService()
