services:
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: "maddy"
      ROUNDCUBEMAIL_DEFAULT_PORT: 143
      ROUNDCUBEMAIL_SMTP_SERVER: "maddy"
      ROUNDCUBEMAIL_SMTP_PORT: 587
      ROUNDCUBEMAIL_USERNAME_DOMAIN: "${HOMELAB_HOSTNAME}"
      ROUNDCUBEMAIL_PLUGINS: "archive,zipdownload,carddav"
    volumes:
      - ${PROJECT_ROOT}/roundcube/volumes/data:/var/www/html
      - ${PROJECT_ROOT}/roundcube/volumes/db:/var/roundcube/db
    networks:
      - homelab-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcube.rule=Host(`${ROUNDCUBE_SERVICE_NAME}.${HOMELAB_HOSTNAME}`)"
      - "traefik.http.routers.roundcube.entrypoints=websecure"
      - "traefik.http.routers.roundcube.tls=true"
      - "traefik.http.routers.roundcube.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"
      - "traefik.http.routers.roundcube.service=roundcube"
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"

networks:
  homelab-net:
    external: true
    name: homelab-net
