# docker-compose.yml
include:
  - ./traefik/compose.yaml
  - ./unbound/compose.yaml
  - ./pihole/compose.yaml
  - ./authentik/compose.yaml
  - ./gatus/compose.yaml
  - ./dashboard/compose.yaml
  - ./dockhand/compose.yaml
  - ./alerts/compose.yaml
  - ./vaultwarden/compose.yaml
  - ./gotify/compose.yaml
  - ./samba/compose.yaml
  - ./sftpgo/compose.yaml
  - ./radicale/compose.yaml
  - ./rustdesk/compose.yaml
  - ./ddclient/compose.yaml
  - ./ollama/compose.yaml
  - ./headscale/compose.yaml
  - ./roundcube/compose.yaml
  - ./maddy/compose.yaml
