# docker-compose.yml
include:
  - ./compose/core/compose.yaml
  - ./compose/dns/compose.yaml
  - ./compose/auth/compose.yaml
  - ./compose/monitoring/compose.yaml
  - ./compose/dashboard/compose.yaml
  - ./compose/docker/compose.yaml
  - ./compose/apps/compose.yaml