# docker-compose.yml
include:
  - ./traefik/compose.yaml
  - ./unbound/compose.yaml
  - ./pihole/compose.yaml
  - ./authentik/compose.yaml
  - ./gatus/compose.yaml
  - ./homelab-dashboard/compose.yaml
  - ./dockhand/compose.yaml
  - ./apprise/compose.yaml
  - ./vaultwarden/compose.yaml
  - ./gotify/compose.yaml
  - ./nextcloud/compose.yaml
  - ./collabora/compose.yaml
  - ./rustdesk/compose.yaml
  - ./ddclient/compose.yaml
  - ./ollama/compose.yaml
