# vaultwarden/compose.yaml
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ${PROJECT_ROOT}/vaultwarden/volumes/data:/data
      - ${PROJECT_ROOT}/volumes/certificates/homelab-ca.crt:/etc/ssl/certs/homelab-ca.crt:ro
    extra_hosts:
      - "${AUTHENTIK_SERVICE_NAME}.${HOMELAB_HOSTNAME}:${TRAEFIK_IP_ADDRESS}"
    networks:
      - homelab-net
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/homelab-ca.crt
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN=https://${VAULTWARDEN_SERVICE_NAME}.${HOMELAB_HOSTNAME}
      - SMTP_SSL_CA_CERT=/etc/ssl/certs/homelab-ca.crt
      - SMTP_HOST=alerts
      - SMTP_PORT=8025
      - SMTP_SECURITY=off
      - SMTP_FROM=vaultwarden@${HOMELAB_HOSTNAME}
      - SSO_ENABLED=true
      - SSO_CLIENT_ID=vaultwarden
      - SSO_AUTHORITY=https://${AUTHENTIK_SERVICE_NAME}.${HOMELAB_HOSTNAME}/application/o/vaultwarden/
      - SSO_SCOPES=openid email profile offline_access groups
      - SSO_AUTH_ONLY_NOT_SESSION=true
      - SSO_CLIENT_SECRET_FILE=/run/secrets/vaultwarden_oidc_secret
      - ADMIN_TOKEN_FILE=/run/secrets/vaultwarden_admin_token
    secrets:
      - vaultwarden_oidc_secret
      - vaultwarden_admin_token
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`${VAULTWARDEN_SERVICE_NAME}.${HOMELAB_HOSTNAME}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
    depends_on:
      alerts:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:80/alive" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

secrets:
  vaultwarden_oidc_secret:
    file: ${PROJECT_ROOT}/volumes/secrets/vaultwarden_oidc_secret
  vaultwarden_admin_token:
    file: ${PROJECT_ROOT}/volumes/secrets/vaultwarden_admin_token

networks:
  homelab-net:
    external: true
