"""Vaultwarden setup — environment secrets configuration."""
import os
import secrets
import shlex
from setup_utils import run_cmd


def setup(env):
    """Generate secure Argon2 hash of the plain-text token and write it to vaultwarden_admin_token."""
    print("\n🔐 Preparing Vaultwarden admin token...")
    
    os.makedirs("./volumes/secrets", exist_ok=True)
    
    # Read the plain-text token generated by setup.py
    plain_token_path = "./volumes/secrets/vaultwarden_admin_token_plain"
    if os.path.exists(plain_token_path):
        with open(plain_token_path, "r") as f:
            plain_token = f.read().strip()
    else:
        # Fallback if file doesn't exist
        plain_token = secrets.token_hex(24)
        with open(plain_token_path, "w") as f:
            f.write(plain_token)
        os.chmod(plain_token_path, 0o600)
    
    admin_token_val = plain_token
    
    # Generate Argon2 hash of the plain-text token
    print("   Generating secure Argon2 hash for Vaultwarden ADMIN_TOKEN...")
    try:
        # Generate a random 8-byte (16 hex character) salt
        salt = secrets.token_hex(8)
        hashed = run_cmd(f"echo -n {shlex.quote(plain_token)} | argon2 {salt} -id -e")
        if hashed:
            admin_token_val = hashed.strip()
            print("   ✅ Secure Argon2 hash generated for ADMIN_TOKEN")
        else:
            print("   ⚠️  Failed to generate Argon2 hash. Using plain text fallback.")
    except Exception as e:
        print(f"   ⚠️  Failed to generate Argon2 hash: {e}. Using plain text fallback.")
    
    # Write the Argon2 hash to vaultwarden_admin_token (which will be mounted as a Docker secret)
    token_path = "./volumes/secrets/vaultwarden_admin_token"
    with open(token_path, "w") as f:
        f.write(admin_token_val)
    os.chmod(token_path, 0o600)
    
    # Delete vaultwarden.env if it exists to avoid conflicts
    env_path = "./volumes/secrets/vaultwarden.env"
    if os.path.exists(env_path):
        os.remove(env_path)
    
    print("   ✅ Vaultwarden admin token secret file prepared successfully")
