"""Radicale CalDAV/CardDAV service — user htpasswd provisioning from shared accounts."""
from __future__ import annotations

import base64
import hashlib
import os

from setup.file_accounts import read_accounts_env
from setup.service import Service, VolumeDir
from setup.ui import ok, section


def _sha1_password(password: str) -> str:
    sha = hashlib.sha1(password.encode("utf-8")).digest()
    return "{SHA}" + base64.b64encode(sha).decode("utf-8")


class RadicaleService(Service):
    name = "radicale"
    volume_dirs = [
        VolumeDir("./radicale/volumes/config", mode=0o755),
        VolumeDir("./radicale/volumes/collections", mode=0o700),
    ]

    def setup(self, env: dict) -> None:
        super().setup(env)
        section("Syncing Radicale users and generating config...", emoji="📅")

        # 1. Read shared accounts
        accounts = read_accounts_env()

        # 2. Backfill primary admin if not present
        admin_user = env.get("HOMELAB_USERNAME") or os.environ.get("HOMELAB_USERNAME")
        if admin_user:
            admin_user = admin_user.lower()
            if admin_user not in accounts:
                pw_path = "./volumes/secrets/homelab_password"
                if os.path.isfile(pw_path):
                    with open(pw_path, encoding="utf-8") as f:
                        admin_pw = f.read().strip()
                    if admin_pw:
                        accounts[admin_user] = admin_pw

        # 3. Generate htpasswd contents
        htpasswd_lines = []
        for username, password in sorted(accounts.items()):
            hashed_pw = _sha1_password(password)
            htpasswd_lines.append(f"{username}:{hashed_pw}")

        # 4. Write users file
        users_path = "./radicale/volumes/config/users"
        with open(users_path, "w", encoding="utf-8") as f:
            f.write("\n".join(htpasswd_lines) + "\n")
        os.chmod(users_path, 0o600)
        ok(f"Wrote {users_path} ({len(htpasswd_lines)} accounts synced)")

        # 5. Write radicale config
        config_content = """# Generated by radicale/setup.py — do not edit manually.
[server]
hosts = 0.0.0.0:5232
base_prefix = /radicale/

[auth]
type = htpasswd
htpasswd_filename = /etc/radicale/users
htpasswd_encryption = sha1

[storage]
type = filesystem
filesystem_folder = /data/collections
"""
        config_path = "./radicale/volumes/config/config"
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(config_content)
        os.chmod(config_path, 0o644)
        ok(f"Wrote {config_path}")


service = RadicaleService()
