"""Radicale CalDAV/CardDAV service — user htpasswd provisioning from shared accounts."""
from __future__ import annotations

import os

from setup.file_accounts import read_accounts_json
from setup.service import Service, VolumeDir
from setup.ui import ok, section
from setup.utils import run_cmd

# UID/GID of the radicale user inside tomsquest/docker-radicale
_RADICALE_UID = 2999


def compile_radicale_configs(env: dict, users: list[dict]) -> None:
    # 1. Backfill primary admin user if not already in users list
    accounts = {u["username"]: u["password"] for u in users}
    admin_user = env.get("HOMELAB_USERNAME") or os.environ.get("HOMELAB_USERNAME")
    if admin_user:
        admin_user = admin_user.lower()
        if admin_user not in accounts:
            pw_path = "./volumes/secrets/homelab_password"
            if os.path.isfile(pw_path):
                with open(pw_path, encoding="utf-8") as f:
                    admin_pw = f.read().strip()
                if admin_pw:
                    accounts[admin_user] = admin_pw

    # 2. Generate plain htpasswd contents
    htpasswd_lines = []
    for username, password in sorted(accounts.items()):
        htpasswd_lines.append(f"{username}:{password}")

    # 3. Write users file
    users_path = "./radicale/volumes/config/users"
    run_cmd(f"sudo chown {os.getuid()}:{os.getgid()} {users_path} 2>/dev/null || true")
    with open(users_path, "w", encoding="utf-8") as f:
        f.write("\n".join(htpasswd_lines) + "\n")
    os.chmod(users_path, 0o600)
    run_cmd(f"sudo chown {_RADICALE_UID}:{_RADICALE_UID} {users_path}")
    ok(f"Wrote {users_path} ({len(htpasswd_lines)} accounts synced)")

    # 4. Write radicale config
    config_content = """# Generated by radicale/setup.py — do not edit manually.
[server]
hosts = 0.0.0.0:5232

[auth]
type = htpasswd
htpasswd_filename = /config/users
htpasswd_encryption = plain

[storage]
type = multifilesystem
filesystem_folder = /data/collections
"""
    config_path = "./radicale/volumes/config/config"
    run_cmd(f"sudo chown {os.getuid()}:{os.getgid()} {config_path} 2>/dev/null || true")
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(config_content)
    os.chmod(config_path, 0o600)
    run_cmd(f"sudo chown {_RADICALE_UID}:{_RADICALE_UID} {config_path}")
    ok(f"Wrote {config_path}")


class RadicaleService(Service):
    name = "radicale"
    volume_dirs = [
        VolumeDir("./radicale/volumes/config", mode=0o755),
        VolumeDir("./radicale/volumes/collections", mode=0o700),
    ]

    def setup(self, env: dict) -> None:
        super().setup(env)
        section("Syncing Radicale users and generating config...", emoji="📅")

        # Ensure the collections directory is owned by the Radicale container user
        # so it can create its lock file and write calendar/contact data.
        collections_dir = "./radicale/volumes/collections"
        run_cmd(f"sudo chown -R {_RADICALE_UID}:{_RADICALE_UID} {collections_dir}")

        users = read_accounts_json()
        compile_radicale_configs(env, users)

    def sync_accounts(self, env: dict, users: list[dict]) -> bool:
        compile_radicale_configs(env, users)
        return True


service = RadicaleService()
