# compose/docker-compose.apps.yml
services:
  rustdesk-id-server:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-id-server
    command: hbbs -r rustdesk-relay-server:21119 -k _
    volumes:
      - rustdesk_data:/root
    networks:
      - homelab-net
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21118:21118"
    restart: unless-stopped
    depends_on:
      - rustdesk-relay-server

  rustdesk-relay-server:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-relay-server
    command: hbbr -k _
    volumes:
      - rustdesk_data:/root
    networks:
      - homelab-net
    ports:
      - "21117:21117"
      - "21119:21119"
    restart: unless-stopped

  homelab-dashboard:
    container_name: homelab-dashboard
    restart: on-failure
    build:
      context: ..
      dockerfile: homelab-dashboard/api/Dockerfile
      args:
        - VITE_DASHBOARD_WEB_HOSTNAME=${VITE_DASHBOARD_WEB_HOSTNAME}
        - VITE_PIHOLE_WEB_HOSTNAME=${VITE_PIHOLE_WEB_HOSTNAME}
        - VITE_NETDATA_WEB_HOSTNAME=${VITE_NETDATA_WEB_HOSTNAME}
        - VITE_PORTAINER_WEB_HOSTNAME=${VITE_PORTAINER_WEB_HOSTNAME}
        - VITE_VAULTWARDEN_WEB_HOSTNAME=${VITE_VAULTWARDEN_WEB_HOSTNAME}
        - VITE_UPTIME_KUMA_WEB_HOSTNAME=${VITE_UPTIME_KUMA_WEB_HOSTNAME}
        - VITE_NTFY_WEB_HOSTNAME=${VITE_NTFY_WEB_HOSTNAME}
        - VITE_LLDAP_WEB_HOSTNAME=${VITE_LLDAP_WEB_HOSTNAME}
        - VITE_AUTHELIA_WEB_HOSTNAME=${VITE_AUTHELIA_WEB_HOSTNAME}
    volumes:
      - dashboard_api_data:/app/api/data
      - dashboard_word_games_data:/app/word_games/data
      - ../volumes/certificates/homelab-ca.crt:/etc/ssl/certs/homelab-ca.crt:ro
    networks:
      - homelab-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${AUTHELIA_WEB_HOSTNAME}:10.10.30.100"
    environment:
      - HOMELAB_API_SESSION_SECRET=${HOMELAB_API_SESSION_SECRET}
      - AUTHELIA_WEB_HOSTNAME=${AUTHELIA_WEB_HOSTNAME}
      - DASHBOARD_WEB_HOSTNAME=${DASHBOARD_WEB_HOSTNAME}
      - DASHBOARD_OIDC_SECRET=${DASHBOARD_OIDC_SECRET}
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/homelab-ca.crt
      - NTFY_ADMIN_TOKENS=${NTFY_ADMIN_TOKENS}
    depends_on:
      authelia:
        condition: service_healthy
    healthcheck:
      test: "wget -qO - http://127.0.0.1:5000 || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

  ddclient:
    build:
      context: ../ddclient
    container_name: ddclient
    restart: on-failure
    environment:
      - TZ=${TZ}
    networks:
      - homelab-net
    healthcheck:
      test: ["CMD-SHELL", "pgrep ddclient || exit 1"]
      interval: 5m
      timeout: 10s
      retries: 2
      start_period: 1m

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: on-failure
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - homelab-net
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: on-failure
    volumes:
      - vaultwarden_data:/data
    networks:
      - homelab-net
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=true
      - DOMAIN=https://${VAULTWARDEN_WEB_HOSTNAME}
      - SMTP_SSL_CA_CERT=/etc/ssl/certs/homelab-ca.crt
      - SMTP_HOST=ntfy
      - SMTP_PORT=25
      - SMTP_SECURITY=off
      - SMTP_FROM=vaultwarden@${HOMELAB_HOSTNAME}
      - SMTP_USERNAME=${HOMELAB_USERNAME}
      - SMTP_PASSWORD=${HOMELAB_PASSWORD}
    depends_on:
      ntfy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/alive"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: on-failure
    volumes:
      - ntfy_data:/var/lib/ntfy
    environment:
      - NTFY_BASE_URL=https://${NTFY_WEB_HOSTNAME}
      - NTFY_AUTH_FILE=/var/lib/ntfy/user.db
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_AUTH_USERS=${NTFY_ADMIN_USERS}
      - NTFY_AUTH_TOKENS=${NTFY_ADMIN_TOKENS}
      - NTFY_BEHIND_PROXY=true
      - NTFY_ENABLE_LOGIN=true
      - NTFY_SMTP_SERVER_LISTEN=:25
      - NTFY_SMTP_SERVER_DOMAIN=${HOMELAB_HOSTNAME}
    networks:
      - homelab-net
    command: serve
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/v1/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    hostname: ${HOMELAB_HOSTNAME}
    pid: host
    restart: on-failure
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/log:/host/var/log:ro
      - /run/dbus:/run/dbus:ro
    networks:
      - homelab-net
    healthcheck:
      test: "curl -f http://localhost:19999/api/v1/info || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

  portainer:
    build: ../portainer
    container_name: portainer
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ../volumes/certificates/homelab-ca.crt:/etc/ssl/certs/homelab-ca.crt:ro
    networks:
      - homelab-net
    extra_hosts:
      - "${AUTHELIA_WEB_HOSTNAME}:10.10.30.100"
    depends_on:
      authelia:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/status"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../volumes/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../volumes/certificates/homelab-ca.crt:/etc/ssl/certs/homelab-ca.crt:ro
    environment:
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/homelab-ca.crt
    networks:
      - homelab-net
    depends_on:
      ntfy:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost:3001 || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m