# compose/docker-compose.auth.yml
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: on-failure
    networks:
      - homelab-net
    volumes:
      - authelia_data:/var/lib/authelia
      - ../volumes/authelia/configuration.yml:/config/configuration.yml:ro
      - ../volumes/secrets:/secrets:ro
      - ../volumes/authelia/private.pem:/config/jwks/private.pem:ro
    depends_on:
      lldap:
        condition: service_healthy
      authelia-redis:
        condition: service_healthy
      ntfy:
        condition: service_healthy
    extra_hosts:
      - "${AUTHELIA_WEB_HOSTNAME}:10.10.30.100"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`${AUTHELIA_WEB_HOSTNAME}`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9091/api/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

  authelia-redis:
    image: redis:7-alpine
    container_name: authelia-redis
    restart: on-failure
    volumes:
      - authelia_redis_data:/data
    networks:
      - homelab-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  lldap:
    image: lldap/lldap:latest
    container_name: lldap
    restart: on-failure
    volumes:
      - lldap_data:/data
      - ../volumes/secrets:/secrets:ro
    networks:
      - homelab-net
    environment:
      - TZ=${TZ}
      - LLDAP_JWT_SECRET_FILE=/secrets/lldap_jwt_secret
      - LLDAP_LDAP_BASE_DN=${LLDAP_LDAP_BASE_DN}
      - LLDAP_LDAP_USER_PASS_FILE=/secrets/lldap_ldap_user_pass
      - LLDAP_HTTP_URL=https://${LLDAP_WEB_HOSTNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lldap.rule=Host(`${LLDAP_WEB_HOSTNAME}`)"
      - "traefik.http.routers.lldap.entrypoints=websecure"
      - "traefik.http.routers.lldap.tls=true"
      - "traefik.http.services.lldap.loadbalancer.server.port=17170"
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:17170/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m