services:
  snappymail:
    image: djmaze/snappymail:latest
    container_name: snappymail
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      SSL_CERT_FILE: /etc/ssl/certs/homelab-ca.crt
      CURL_CA_BUNDLE: /etc/ssl/certs/homelab-ca.crt
    volumes:
      - ${PROJECT_ROOT}/volumes/certificates/homelab-ca.crt:/etc/ssl/certs/homelab-ca.crt:ro
      - ${PROJECT_ROOT}/snappymail/volumes/data:/var/lib/snappymail
    networks:
      - homelab-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snappymail.rule=Host(`${SNAPPYMAIL_SERVICE_NAME}.${HOMELAB_HOSTNAME}`)"
      - "traefik.http.routers.snappymail.entrypoints=websecure"
      - "traefik.http.routers.snappymail.tls=true"
      - "traefik.http.routers.snappymail.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"
      - "traefik.http.routers.snappymail.service=snappymail"
      - "traefik.http.services.snappymail.loadbalancer.server.port=8888"

networks:
  homelab-net:
    external: true
    name: homelab-net
