# ollama/compose.yaml
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ${PROJECT_ROOT}/services/ollama/volumes/ollama:/root/.ollama
    networks:
      - homelab-net
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

networks:
  homelab-net:
    external: true
