# compose/docker/compose.yaml
services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data
    networks:
      - homelab-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockhand.rule=Host(`${DOCKHAND_SERVICE_NAME}.${HOMELAB_HOSTNAME}`)"
      - "traefik.http.routers.dockhand.entrypoints=websecure"
      - "traefik.http.routers.dockhand.tls=true"
      - "traefik.http.routers.dockhand.middlewares=authentik-auth@file"
      - "traefik.http.services.dockhand.loadbalancer.server.port=3000"
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:3000" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

volumes:
  dockhand_data:

networks:
  homelab-net:
    external: true
